name: RadEndpoints Publish

on: #workflow_dispatch
  push:
    tags:
      - '*.*.**'

jobs:
  publish_nuget:
    name: Publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set Version
        run: |
          sed -i -e 's/{{Version}}/${{ github.ref_name }}/' ./RadEndpoints/RadEndpoints.csproj
          sed -i -e 's/{{Version}}/${{ github.ref_name }}/' ./RadEndpoints.Testing/RadEndpoints.Testing.csproj
          cat ./RadEndpoints/RadEndpoints.csproj

      - name: Pack
        run: |
          dotnet pack -c Release -o ./artifacts

      # - name: Publish
      #   env: 
      #     NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      #   run: |
      #     dotnet nuget push ./artifacts/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
      